### ISSUE TITLE
fail to run the phakinpro.py

### ISSUE THREAD

**Issue by MachineGUN001** [jimmyjbling/PhaKinPro#1]
hi, 

thanks for providing such interesting work.

as the Readme file mentioned, I try to run

`!python ./PhaKinPro/phakinpro.py --help`

the script cannot work, could you please help recheck the code if it can work. thanks

Best,

**Comment by xx927** [comment]
me too, there is an error that "No such file or directory"

**Comment by jimmyjbling** [comment]
Currently, PhaKinPro requires that the model are downloaded too (in the model dir of the repo) and that you call the the function from the repository that has the model dir. I suspect this is where the error is coming from.

I agree that is is bad, I'll make an update so you can call it from any directory

**Comment by MachineGUN001** [comment]
thanks!
